// CSS Module: home.module.css — auto-generated by BertUI
const styles = {
  "hero": "hero_qymhg",
  "heroInner": "heroInner_cfvuk",
  "badge": "badge_gnd8b",
  "title": "title_gdbhq",
  "gradient": "gradient_igq8d",
  "subtitle": "subtitle_h08o3",
  "actions": "actions_vbb5r",
  "stats": "stats_gdond",
  "stat": "stat_qytt1",
  "statValue": "statValue_dt4lf",
  "statLabel": "statLabel_dymr5"
};
export default styles;
