// CSS Module: layout.module.css — auto-generated by BertUI
const styles = {
  "layout": "layout_adoj4",
  "sidebar": "sidebar_2hdsz",
  "main": "main_a7knp",
  "logo": "logo_a7l0c",
  "logoIcon": "logoIcon_nzngy",
  "logoText": "logoText_nzuji",
  "logoName": "logoName_nzqmc",
  "logoVersion": "logoVersion_wr56f",
  "nav": "nav_ovi7n",
  "navSection": "navSection_9wkpb",
  "navLabel": "navLabel_osfdq",
  "navLink": "navLink_8d5ns",
  "navLinkActive": "navLinkActive_ffdp4",
  "footer": "footer_d0ffq",
  "githubLink": "githubLink_vu2io",
  "mobileToggle": "mobileToggle_dut3c",
  "sidebarOpen": "sidebarOpen_wzi7k"
};
export default styles;
